language: python

python:
    - 2.6
    - 2.7
    - 3.3

env:
    # try all python versions with the latest stable numpy and astropy

    - ASTROPY_VERSION=development NUMPY_VERSION=1.8.0 SETUP_CMD='test'

matrix:
    include:
        - python: 2.7
          env: ASTROPY_VERSION=development NUMPY_VERSION=1.8.0 SETUP_CMD='test --coverage'

        - python: 2.7
          env: SCIPY_VERSION=0.9.3 ASTROPY_VERSION=development NUMPY_VERSION=1.8.0 SETUP_CMD='test --coverage'

before_install:
   # We do this to make sure we get the dependencies so pip works below
   - sudo apt-get update -qq
   - sudo apt-get install -qq python-numpy python-sphinx cython libatlas-dev liblapack-dev gfortran
   - if [[ $SETUP_CMD == build_sphinx* ]]; then sudo apt-get install -qq python-sphinx graphviz texlive-latex-extra dvipng python-matplotlib; fi

install:
   - export PYTHONIOENCODING=UTF8 # just in case
   - pip -q install --upgrade "numpy==$NUMPY_VERSION" --use-mirrors
   - pip -q install --upgrade Cython --use-mirrors
   - pip -q install --upgrade pytest --use-mirrors
   - if [[ $SETUP_CMD == build_sphinx* ]]; then pip -q install sphinx==1.1.3 --use-mirrors; fi
   - if [[ $SETUP_CMD == build_sphinx* ]]; then pip -q install matplotlib --use-mirrors; fi

   - if [[ -n $SCIPY_VERSION]]; then pip -q install "scipy==$SCIPY_VERSION"; fi
   - if [[ $ASTROPY_VERSION == stable ]]; then pip -q install astropy --use-mirrors; fi
   - if [[ $ASTROPY_VERSION == development ]]; then pip -q install git+http://github.com/astropy/astropy.git#egg=astropy --use-mirrors; fi
   - if [[ $SETUP_CMD == 'test --coverage' ]]; then pip -q install coveralls --use-mirrors; fi
   - if [[ $SETUP_CMD == 'test --coverage' ]]; then pip -q install pytest-cov --use-mirrors; fi

script:
   - python setup.py $SETUP_CMD

after_success:
   - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls; fi

